version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./api:/api
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - api
    networks:
      - backend-network

  mysql:
    image: mysql:latest
    ports:
      - "3036:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "container-root-password"
      MYSQL_DATABASE: "accounting-db"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend-network

  api:
    build: ./api
    volumes:
      - ./api:/api
    links:
      - mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql:
