version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./api:/api
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./api
    volumes:
      - ./api:/api

  node:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
    environment:
      - CHOKIDAR_USEPOLLING=true
