name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: generate dotenv
      run: cp api/.env.sample api/.env

    - name: Build Docker environment
      run: make up

    - name: Init BE
      run: make init-be

    - name: run phpunit
      run: make test-unit

